import type { EventT, Notif, User } from "./types";
import { at, HOUR, MIN } from "./util";

export const ME = "me";

export const USERS: User[] = [
  {
    id: ME,
    name: "Nath",
    handle: "nathcury",
    emoji: "🫶",
    gradient: ["#8A6CFF", "#FF6A8E"],
    city: "Stuttgart",
    bio: "Always in for the weird ones. 🇧🇷→🇩🇪",
    birthday: { month: 5, day: 13 },
    mutuals: 0,
    mood: "open",
  },
  { id: "felice", name: "Felice", handle: "feliceee", emoji: "🌶️", gradient: ["#FF6A5C", "#FFC65C"], city: "Stuttgart", mutuals: 12, mood: "open", birthday: { month: 6, day: 16 } },
  { id: "erick", name: "Erick", handle: "erick.mov", emoji: "🛹", gradient: ["#3EE6A0", "#0EA5E9"], city: "Stuttgart", mutuals: 9, mood: "lazy-week", birthday: { month: 6, day: 10 } },
  { id: "pippo", name: "Pippo Taylor", handle: "pippo_t", emoji: "🎷", gradient: ["#FFC65C", "#FF6AC2"], city: "Stuttgart", mutuals: 7, mood: "open" },
  { id: "reduque", name: "Re Duque", handle: "re_duque", emoji: "🧿", gradient: ["#7A3CFF", "#00D4FF"], city: "Stuttgart", mutuals: 4, mood: "not-today" },
  { id: "alexw", name: "Alex Willrich", handle: "alexwill", emoji: "🦊", gradient: ["#FF7A3C", "#E0589C"], city: "Stuttgart", mutuals: 1 },
  { id: "naomi", name: "Naomi", handle: "naomi.naomi", emoji: "🌙", gradient: ["#5C6CFF", "#3EE6A0"], city: "Berlin", mutuals: 1 },
  { id: "bernd", name: "Bernd", handle: "bernd_b", emoji: "🧗", gradient: ["#0EA5E9", "#8A6CFF"], city: "Stuttgart", mutuals: 1 },
  { id: "mare", name: "Mare", handle: "mare.wav", emoji: "🌊", gradient: ["#00D4FF", "#3EE6A0"], city: "Stuttgart", mutuals: 1, birthday: { month: 6, day: 21 } },
  { id: "pato", name: "Pato LD", handle: "pato_ld", emoji: "🦆", gradient: ["#FFC65C", "#7AC943"], city: "Stuttgart", mutuals: 3, birthday: { month: 6, day: 25 }, mood: "open" },
  { id: "joan", name: "Joanginer", handle: "joanginer", emoji: "🍊", gradient: ["#FF6A5C", "#8A6CFF"], city: "Stuttgart", mutuals: 2 },
  { id: "matti", name: "Matt I", handle: "matt_i", emoji: "🎲", gradient: ["#9E9CAF", "#5C6CFF"], city: "Stuttgart", mutuals: 2 },
  { id: "plmnt", name: "Plmntt", handle: "plmntt", emoji: "🌱", gradient: ["#7AC943", "#3EE6A0"], city: "Stuttgart", mutuals: 2 },
  {
    id: "wizemann",
    name: "Im Wizemann",
    handle: "imwizemann",
    emoji: "🏭",
    gradient: ["#2E2A5C", "#8A6CFF"],
    city: "Stuttgart",
    mutuals: 0,
    organizer: true,
    verified: true,
    bio: "Venue · Stuttgart Nord",
  },
  {
    id: "karle",
    name: "Karle Kollektiv",
    handle: "karlekollektiv",
    emoji: "☄️",
    gradient: ["#FF3C8E", "#7A3CFF"],
    city: "Stuttgart",
    mutuals: 0,
    organizer: true,
    verified: true,
    bio: "Soli parties & open airs",
  },
];

export const DEFAULT_FOLLOWING = ["felice", "erick", "pippo", "pato", "wizemann", "karle"];

const E = (e: Partial<EventT> & Pick<EventT, "id" | "title" | "emoji" | "vibe" | "start" | "end" | "city" | "privacy" | "createdBy">): EventT => ({
  art: 1,
  coCreators: [],
  going: [],
  maybe: [],
  invited: [],
  bringEnabled: false,
  bring: [],
  expenses: [],
  comments: [],
  predictions: [],
  photos: [],
  pacts: [],
  radar: {},
  exitPoll: {},
  ...e,
});

export const seedEvents = (): EventT[] => [
  // ───────── LIVE right now ─────────
  E({
    id: "vorsicht",
    title: "VORSICHT DRAUFSICHT — Soli Party",
    emoji: "⚠️",
    art: 7,
    vibe: "party",
    start: Date.now() - 1.5 * HOUR,
    end: Date.now() + 4.5 * HOUR,
    venue: "Im Wizemann, Halle",
    city: "Stuttgart",
    description:
      "Soli party for the Draufsicht collective. Two floors, techno up top, disco in the basement. All door money goes to the crew. Bring cash, bring friends, bring earplugs.",
    privacy: "public",
    createdBy: "karle",
    going: ["me", "felice", "pippo", "reduque", "mare"],
    maybe: ["erick", "joan"],
    invited: ["me", "felice", "erick", "pippo"],
    weather: { icon: "🌙", temp: 17, label: "Clear night" },
    lineMode: true,
    lineLevel: 2,
    lineReports: 6,
    radar: { felice: "there", pippo: "there", reduque: "otw", mare: "home" },
    comments: [
      { id: "c1", by: "felice", text: "basement floor is INSANE come now", ts: Date.now() - 40 * MIN },
      { id: "c2", by: "pippo", text: "@felice saving you a spot at the bar 🍻", ts: Date.now() - 22 * MIN },
    ],
    predictions: [
      { id: "p1", by: "felice", text: "Nath will say 'one more song' at least 4 times." },
      { id: "p2", by: "me", text: "Bet we end up way closer to the stage than planned." },
    ],
    expenses: [
      { id: "x1", amount: 18, label: "Taxi to venue", paidBy: "felice", among: ["me", "felice", "pippo"], ts: Date.now() - HOUR },
    ],
    views: 412,
    sourceUrl: "https://ra.co/events/vorsicht-draufsicht",
    sourceType: "url",
  }),
  // ───────── yesterday (after-flow showcase) ─────────
  E({
    id: "karaoke",
    title: "Küchen Karaoke Night",
    emoji: "🎤",
    art: 3,
    vibe: "party",
    start: at(-1, 20),
    end: at(-1, 23, 30),
    venue: "Felice's place, Stuttgart West",
    city: "Stuttgart",
    description: "Kitchen karaoke. The neighbours have been warned. Songs in any language, courage mandatory.",
    privacy: "circle",
    createdBy: "felice",
    going: ["me", "felice", "erick", "pippo", "pato"],
    maybe: [],
    invited: ["me", "erick", "pippo", "pato"],
    predictions: [
      { id: "kp1", by: "erick", text: "Pippo will cry during a ballad. Calling it now." },
      { id: "kp2", by: "me", text: "Felice sings ABBA before 22:00. Guaranteed." },
      { id: "kp3", by: "pato", text: "We order pizza at exactly 22:47." },
    ],
    exitPoll: { felice: "fire", erick: "fire", pippo: "mid" },
    photos: [
      { id: "kf1", by: "felice", seed: 11, emoji: "🎤" },
      { id: "kf2", by: "erick", seed: 23, emoji: "🍕" },
    ],
    expenses: [
      { id: "kx1", amount: 34.5, label: "Pizza for everyone", paidBy: "me", among: ["me", "felice", "erick", "pippo", "pato"], ts: at(-1, 22) },
      { id: "kx2", amount: 12, label: "Limoncello", paidBy: "pippo", among: ["me", "felice", "erick", "pippo"], ts: at(-1, 21) },
    ],
    weather: { icon: "🌧️", temp: 14, label: "Light rain" },
  }),
  // ───────── upcoming ─────────
  E({
    id: "flohmarkt",
    title: "Flohmarkt am Feuersee",
    emoji: "🛍️",
    art: 4,
    vibe: "market",
    start: at(1, 10),
    end: at(1, 16),
    venue: "Platz am Feuersee",
    city: "Stuttgart",
    description: "Sunday flea market around the lake. Vintage cameras, bad paintings, great coffee. Come early or cry about the good stuff being gone.",
    privacy: "circle",
    createdBy: "me",
    going: ["me", "reduque"],
    maybe: ["felice", "erick"],
    invited: ["felice", "erick", "reduque", "pippo"],
    pacts: [
      { id: "fp1", between: ["pippo", "joan"], status: "pending" },
      { id: "fp2", between: ["mare", "matti"], status: "pending" },
      { id: "fp3", between: ["bernd", "plmnt"], status: "pending" },
    ],
    weather: { icon: "⛅", temp: 21, label: "Partly cloudy" },
    sourceType: "screenshot",
  }),
  E({
    id: "sixeuro",
    title: "6EURONEUNZIG",
    emoji: "🎸",
    art: 9,
    vibe: "concert",
    start: at(3, 20),
    end: at(3, 23, 59),
    venue: "Im Wizemann",
    city: "Stuttgart",
    description:
      "6euroneunzig, das klingt so als würden Blümchen, Ikkimel und SXTN in einem besetzten Haus in der Rigaer zusammen Musik machen. Tussitechno, Fotzenrap & Pussypop — selbstironische Lyrics, unschuldige Melodien und ein dicker Mittelfinger an alle Faschos dieser Welt. »Die Message darf nie fehlen, aber noch viel wichtiger ist, dass wir Spaß haben.«",
    privacy: "public",
    createdBy: "wizemann",
    going: ["felice", "mare", "joan"],
    maybe: ["me", "reduque"],
    invited: [],
    weather: { icon: "☁️", temp: 17, label: "Cloudy" },
    lineMode: true,
    lineLevel: 0,
    views: 289,
    ticket: "https://imwizemann.de/tickets",
    sourceUrl: "https://imwizemann.de/events/6euroneunzig",
    sourceType: "url",
    comments: [{ id: "sc1", by: "mare", text: "their last show sold out, get tickets NOW", ts: at(-1, 12) }],
  }),
  E({
    id: "lakerun",
    title: "Morning Lake Run",
    emoji: "🏃",
    art: 2,
    vibe: "run",
    start: at(5, 8),
    end: at(5, 9, 30),
    venue: "Max-Eyth-See, north entrance",
    city: "Stuttgart",
    description: "Easy 6k around the lake, then coffee at the kiosk. No pace pressure — we wait for everyone.",
    privacy: "circle",
    createdBy: "erick",
    going: ["erick", "bernd"],
    maybe: ["me"],
    invited: ["me", "felice", "bernd"],
    pacts: [{ id: "pa1", between: ["me", "felice"], status: "pending" }],
    weather: { icon: "☀️", temp: 16, label: "Sunny morning" },
  }),
  E({
    id: "brunch",
    title: "Sunday Brunch Club",
    emoji: "🥐",
    art: 5,
    vibe: "brunch",
    start: at(6, 11),
    end: at(6, 14),
    venue: "Künstlerhaus rooftop",
    city: "Stuttgart",
    description: "Bring-something brunch on the rooftop. We have the coffee machine sorted, the rest is on all of us.",
    privacy: "circle",
    createdBy: "pippo",
    going: ["pippo", "felice", "me"],
    maybe: ["pato"],
    invited: ["me", "felice", "pato", "erick"],
    bringEnabled: true,
    bring: [
      { id: "b1", label: "Sourdough bread", emoji: "🍞", claimedBy: "felice" },
      { id: "b2", label: "Bluetooth speaker", emoji: "🔊", claimedBy: null },
      { id: "b3", label: "Orange juice (2L)", emoji: "🍊", claimedBy: null },
      { id: "b4", label: "Fruit bowl", emoji: "🍓", claimedBy: "pippo" },
      { id: "b5", label: "Oat milk", emoji: "🥛", claimedBy: null },
    ],
    weather: { icon: "☀️", temp: 24, label: "Sunny" },
  }),
  E({
    id: "aboutpop",
    title: "ABOUTPOP Festival",
    emoji: "🎪",
    art: 8,
    vibe: "festival",
    start: at(9, 14),
    end: at(10, 23),
    venue: "Across the city",
    city: "Stuttgart",
    description:
      "Mind Enterprises · Josh Cohen · Das Beat · Agriculture · Grace Ives · Agatha is Dead! · Nightbus · Get Well Soon · Mandhla · Pako Peng · Layla Boe · NESSEL · Städtische Manieren · uvm. Two days, every venue that matters.",
    privacy: "public",
    createdBy: "karle",
    going: ["mare", "joan", "reduque"],
    maybe: ["me", "felice"],
    invited: [],
    views: 1203,
    weather: { icon: "🌤️", temp: 23, label: "Mostly sunny" },
    ticket: "https://aboutpop.de",
  }),
  E({
    id: "patobday",
    title: "Pato's 30th — Lake Edition",
    emoji: "🦆",
    art: 6,
    vibe: "birthday",
    start: at(13, 15),
    end: at(13, 23),
    venue: "Bärensee, the usual spot",
    city: "Stuttgart",
    description: "Pato turns 30 and wants exactly one thing: everyone at the lake, a grill that works, and zero speeches. Presents = no. Memes printed on paper = yes.",
    privacy: "list",
    createdBy: "pato",
    coCreators: ["felice"],
    going: ["pato", "felice", "me", "erick"],
    maybe: ["pippo", "mare"],
    invited: ["me", "felice", "erick", "pippo", "mare", "joan", "matti", "plmnt"],
    bringEnabled: true,
    bring: [
      { id: "pb1", label: "Charcoal + lighter", emoji: "🔥", claimedBy: "erick" },
      { id: "pb2", label: "Cake (chocolate!)", emoji: "🎂", claimedBy: null },
      { id: "pb3", label: "Cold beers (crate)", emoji: "🍺", claimedBy: null },
      { id: "pb4", label: "Frisbee", emoji: "🥏", claimedBy: "felice" },
    ],
    predictions: [{ id: "pp1", by: "felice", text: "Pato cries before sunset. Happy tears. 100%." }],
    weather: { icon: "☀️", temp: 26, label: "Sunny" },
  }),
  E({
    id: "csd",
    title: "CSD Stuttgart",
    emoji: "🌈",
    art: 10,
    vibe: "day",
    start: at(43, 12),
    end: at(43, 22),
    venue: "City centre",
    city: "Stuttgart",
    description: "The loudest, proudest day of the year. March first, dance after.",
    privacy: "public",
    createdBy: "karle",
    going: ["me", "felice", "mare"],
    maybe: [],
    invited: [],
    views: 880,
    weather: { icon: "🌈", temp: 25, label: "Perfect" },
  }),
  // ───────── ghost (only me) ─────────
  E({
    id: "ghostcinema",
    title: "Solo Cinema: Wim Wenders retro",
    emoji: "🎬",
    art: 12,
    vibe: "cinema",
    start: at(2, 19, 30),
    end: at(2, 22),
    venue: "Delphi Arthaus Kino",
    city: "Stuttgart",
    description: "Me, popcorn, nobody talking to me. Perfect.",
    privacy: "ghost",
    createdBy: "me",
    going: ["me"],
  }),
  // ───────── past with capsules ─────────
  E({
    id: "greeklish",
    title: "Greeklish Day",
    emoji: "🫒",
    art: 13,
    vibe: "picnic",
    start: at(-18, 12),
    end: at(-18, 18),
    venue: "Killesberg Park",
    city: "Stuttgart",
    description: "Greek picnic — everyone brings one dish their grandma would approve of.",
    privacy: "circle",
    createdBy: "me",
    going: ["me", "felice", "erick", "pato", "reduque"],
    invited: ["felice", "erick", "pato", "reduque"],
    photos: [
      { id: "g1", by: "me", seed: 31, emoji: "🫒" },
      { id: "g2", by: "felice", seed: 47, emoji: "🥗" },
      { id: "g3", by: "erick", seed: 8, emoji: "🌳" },
      { id: "g4", by: "pato", seed: 56, emoji: "🧆" },
      { id: "g5", by: "me", seed: 72, emoji: "☀️" },
      { id: "g6", by: "reduque", seed: 19, emoji: "🍉" },
    ],
    predictions: [
      { id: "gp1", by: "me", text: "Erick brings supermarket tzatziki and claims it's homemade." },
      { id: "gp2", by: "felice", text: "We stay 3 hours longer than planned." },
    ],
    exitPoll: { me: "fire", felice: "fire", erick: "fire", pato: "mid" },
    expenses: [
      { id: "gx1", amount: 24, label: "Picnic snacks", paidBy: "felice", among: ["me", "felice", "erick", "pato"], ts: at(-18, 11) },
      { id: "gx2", amount: 12, label: "Taxi", paidBy: "erick", among: ["me", "erick"], ts: at(-18, 18) },
      { id: "gx3", amount: 18, label: "Drinks", paidBy: "me", among: ["me", "felice", "erick", "pato"], ts: at(-18, 14) },
    ],
    weather: { icon: "☀️", temp: 27, label: "Hot" },
  }),
  E({
    id: "samt",
    title: "Samt für alle",
    emoji: "🪩",
    art: 14,
    vibe: "club",
    start: at(-25, 23),
    end: at(-24, 5),
    venue: "Weißenburg Klub",
    city: "Stuttgart",
    description: "Velvet night. Disco until the lights come on.",
    privacy: "circle",
    createdBy: "felice",
    going: ["me", "felice", "mare"],
    exitPoll: { felice: "fire" },
    photos: [],
  }),
  E({
    id: "obermuehle",
    title: "Opening Obermühle",
    emoji: "🌾",
    art: 15,
    vibe: "day",
    start: at(-42, 14),
    end: at(-42, 22),
    venue: "Obermühle Biergarten",
    city: "Stuttgart",
    description: "Season opening at the mill. First Radler of the year.",
    privacy: "circle",
    createdBy: "pippo",
    going: ["me", "pippo", "felice", "erick", "bernd"],
    photos: [
      { id: "o1", by: "pippo", seed: 41, emoji: "🍻" },
      { id: "o2", by: "me", seed: 28, emoji: "🌾" },
      { id: "o3", by: "felice", seed: 63, emoji: "🌅" },
    ],
    exitPoll: { me: "fire", pippo: "fire", felice: "mid", erick: "fire" },
  }),
  E({
    id: "hoffloh",
    title: "Hofflohmärkte West",
    emoji: "📦",
    art: 16,
    vibe: "market",
    start: at(-48, 11),
    end: at(-48, 17),
    venue: "Stuttgart West, courtyards",
    city: "Stuttgart",
    description: "Courtyard flea markets all over West. Treasure hunting door to door.",
    privacy: "circle",
    createdBy: "me",
    going: ["me", "reduque", "felice"],
    photos: [
      { id: "h1", by: "me", seed: 5, emoji: "🪑" },
      { id: "h2", by: "reduque", seed: 90, emoji: "📚" },
    ],
    exitPoll: { me: "mid", reduque: "fire" },
  }),
];

export const seedNotifs = (): Notif[] => [
  { id: "n1", kind: "line", text: "Door's moving at VORSICHT DRAUFSICHT — short line right now 🚪", ts: Date.now() - 25 * MIN, read: false, eventId: "vorsicht" },
  { id: "n2", kind: "rsvp", text: "Felice is in for Flohmarkt am Feuersee", ts: Date.now() - 2 * HOUR, read: false, eventId: "flohmarkt", userId: "felice" },
  { id: "n3", kind: "pact", text: "Felice proposed a pact for Morning Lake Run — 'I'll go if you go'", ts: Date.now() - 5 * HOUR, read: false, eventId: "lakerun", userId: "felice" },
  { id: "n4", kind: "capsule", text: "Küchen Karaoke capsule just unlocked — 3 predictions revealed 🔮", ts: Date.now() - 9 * HOUR, read: false, eventId: "karaoke" },
  { id: "n5", kind: "tab", text: "Pippo added 'Limoncello' (12,00 €) to the Tab on Küchen Karaoke", ts: at(-1, 21, 12), read: true, eventId: "karaoke", userId: "pippo" },
  { id: "n6", kind: "invite", text: "Pato invited you to Pato's 30th — Lake Edition", ts: at(-2, 17), read: true, eventId: "patobday", userId: "pato" },
  { id: "n7", kind: "birthday", text: "Erick's birthday was 2 days ago — still time for a late card 🙈", ts: at(-2, 9), read: true, userId: "erick" },
  { id: "n8", kind: "tab", text: "Erick paid you back 5,00 € on Greeklish Day", ts: at(-3, 15), read: true, eventId: "greeklish", userId: "erick" },
  { id: "n9", kind: "follow", text: "Re Duque started following you", ts: at(-4, 12), read: true, userId: "reduque" },
  { id: "n10", kind: "reminder", text: "Reminded you about 9,80 € open on Greeklish Day", ts: at(-5, 10), read: true, eventId: "greeklish" },
];

/* templates used by the AI screenshot / URL ingest simulation */
export const PARSE_TEMPLATES = [
  {
    title: "KARAOKE KELLER vol. 4",
    emoji: "🎤",
    vibe: "party" as const,
    venue: "Kellerklub, Marienplatz",
    days: 4,
    hour: 21,
    description: "Basement karaoke, vol. 4. Two mics, zero shame. Entry free before 22:00.",
  },
  {
    title: "Open Air am Fluss",
    emoji: "🌅",
    vibe: "club" as const,
    venue: "Neckarufer, Bad Cannstatt",
    days: 6,
    hour: 16,
    description: "Sundowner open air by the river. House & disco until the city says stop.",
  },
  {
    title: "Vinyl & Vintage Markt",
    emoji: "📀",
    vibe: "market" as const,
    venue: "Wagenhallen",
    days: 8,
    hour: 11,
    description: "Records, tapes and questionable 90s jackets. Bring cash, leave with treasure.",
  },
];
